x-app: &app
  build:
    context: .
    target: base
    args:
      BUILDKIT_INLINE_CACHE: 1
    cache_from:
      - ghcr.io/notch8/archives_online/base:latest
      - ghcr.io/notch8/archives_online:latest
  image: ghcr.io/notch8/archives_online:${TAG:-latest}
  env_file:
    - .env
  volumes:
    - .:/home/app/webapp
    - node_modules:/home/app/webapp/node_modules
    - tmp:/home/app/webapp/tmp
    - public:/app/samvera/hyrax-webapp/public
  networks:
    internal:

volumes:
  mysql:
  node_modules:
  public:
  solr:
  tmp:

networks:
  internal:

services:
  base:
    <<: *app
    image: ghcr.io/notch8/archives_online/base:${TAG:-latest}
    build:
      context: .
      target: base
      cache_from:
        - ghcr.io/notch8/archives_online/base:latest
      args:
        BUILDKIT_INLINE_CACHE: 1

  web:
    <<: *app
    build:
      context: .
      target: web
    expose:
      - 3000
    environment:
      - VIRTUAL_HOST=archives-online.test
      - VIRTUAL_PORT=80
    volumes:
      - ./generate-init.sh:/home/app/webapp/generate-init.sh
    depends_on:
      - mysql
      - solr

  mysql:
    platform: linux/amd64
    image: mysql:8.4.2
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
      # - ./generate-init.sh:/docker-entrypoint-initdb.d/generate-init.sh
    networks:
      - internal

  mailhog:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_PORT=8025
      - VIRTUAL_HOST=mailhog.archives-online.test
    ports:
      - "8025:8025"
    networks:
      - internal

  solr:
    image: solr:8.3
    env_file:
      - .env
    environment:
      - VIRTUAL_PORT=8983
      - VIRTUAL_HOST=solr.archives-online.test
    expose:
      - 8983
    volumes:
      - './solr/conf:/opt/solr/conf'
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ${SOLR_CORE}
      - /opt/solr/conf
      - "-Xms256m"
      - "-Xmx512m"
    networks:
      - internal
